---

name: CWF integ test

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - master
      - quentin-new-ci

jobs:
  cwf-integ-test:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: "20.10"
      - name: setup pyenv
        uses: "gabrielfalcao/pyenv-action@v8"
        with:
          default: 3.8.5
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Install pre requisites
        run: |
          pip3 install --upgrade pip
          pip3 install ansible fabric3 jsonpickle requests PyYAML
          vagrant plugin install vagrant-vbguest vagrant-disksize
      - name: Run docker compose
        run: |
          cd cwf/gateway/docker
          docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.nginx.yml -f docker-compose.integ-test.yml build --force-rm  --parallel
      - name: Run the integ test
        run: |
          cd cwf/gateway
          fab integ_test:destroy_vm=True,transfer_images=True,test_result_xml=tests.xml
