---

name: LTE integ test

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  lte-integ-test:
    runs-on: macos-10.15
    steps:
      - run: echo "::set-output name=date::$(date +'%m-%d-%Y--%H-%M-%S')"
        id: date
      - uses: actions/checkout@v2
      - name: setup pyenv
        uses: "gabrielfalcao/pyenv-action@v8"
        with:
          default: 3.8.5
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Install pre requisites
        run: |
          pip3 install --upgrade pip
          pip3 install ansible fabric3 jsonpickle requests PyYAML
          vagrant plugin install vagrant-vbguest vagrant-disksize
      - name: Run the integ test
        run: |
          cd lte/gateway
          fab integ_test
      - name: Get test results
        if: always()
        run: |
          fab get_test_summaries:dst_path="test-results"
          ls -R
      - name: upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: test-results
      - name: Publish Unit Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: test-results/**/*.xml
